### PR TITLE
Generate consts inside the correct namespace

### LINKED ISSUE #133: Consts in namespaces
Pretty sure that a constant in a namespace currently ends up _not_ being in the namespace in the output Rust code.

I'd mark this as "good first issue" but I'm currently doing quite major surgery in this area.

### PR DESCRIPTION
**Pull request by ssbr**
Fixes #133

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

---

```
test result: ok. 183 passed; 0 failed; 20 ignored; 0 measured; 0 filtered out; finished in 286.38s
```

This change retains the constant inside the bindgen module, and then generates an alias:

```
        mod bindgen {                                                                                  
            pub(super) mod root {                                                                      
                pub mod A {                                                                            
                    pub const kConstant: ::std::os::raw::c_int = 3;                                    
                    #[allow(unused_imports)]                                                           
                    use self::super::super::super::cxxbridge;                                          
                    #[allow(unused_imports)]                                                           
                    use self::super::super::super::ToCppString;                                        
                    #[allow(unused_imports)]       
                    use self::super::super::root;
                }                                                                                      
                #[allow(unused_imports)]                                                               
                use self::super::super::cxxbridge;                                                     
                #[allow(unused_imports)]                                                               
                use self::super::super::ToCppString;                                                   
                #[allow(unused_imports)]
                use self::super::root;                                                                 
            }                                      
        }                                                                                              
        #[cxx::bridge]
        mod cxxbridge {                                                                                
            unsafe extern "C++" {                                                                      
                fn make_string(str_: &str) -> UniquePtr<CxxString>;                                    
                include!("input.h");                                                                   
                include!("autocxxgen.h");          
            }                                      
        }                                                                                              
        #[allow(unused_imports)]            
        use bindgen::root;                         
        pub mod A {                                
            pub use super::bindgen::root::A::kConstant;      
        }
```

### CODE REVIEW

**Comment by adetaylor** [comment]
Thanks for the PR! I'll almost certainly merge this, but first I want to work out why `UsedFromBindgen` didn't work in case it yields any other juicy bugs I should look into.

On the tests, thanks, that's expected. There are a couple of negative tests (i.e. intentionally failing) and I haven't figured out how to suppress their console output yet.

**Comment by ssbr** [comment]
IIUC, it's because it uses the wrong bindgen. This is the output if I do that:

```
[2021-04-27T21:42:11Z INFO  autocxx_engine] Bindings: mod bindgen { /* automatically generated by rust-
bindgen 0.58.2 */                                                                                      
                                                                                                       
    #[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]                             
    pub mod root {                                                                                     
        #[allow(unused_imports)]                                                                       
        use self::super::root;                                                                         
        pub mod A {                                                                                    
            #[allow(unused_imports)]                                                                   
            use self::super::super::root;                                                              
            pub const kConstant: ::std::os::raw::c_int = 3;                                            
        }                                                                                              
    }                                                                                                  
     }  
[...]
[2021-04-27T21:42:11Z INFO  autocxx_engine] New bindings:                                              
    #[allow(non_snake_case)]                                                                           
    #[allow(dead_code)]                                                                                
    #[allow(non_upper_case_globals)]                                                                   
    #[allow(non_camel_case_types)]                                                                     
    mod ffi { 

[...]

        mod bindgen {                                                                                  
            pub(super) mod root {                                                                      
                #[allow(unused_imports)]                                                               
                use self::super::super::cxxbridge;                                                     
                #[allow(unused_imports)]                                                               
                use self::super::super::ToCppString;                                                   
                #[allow(unused_imports)]                                                               
                use self::super::root;             
            }                                                                                          
        }                                                                                              
        #[cxx::bridge]                                                                                 
        mod cxxbridge {                                                                                
            unsafe extern "C++" {                  
                fn make_string(str_: &str) -> UniquePtr<CxxString>;                                    
                include!("input.h");                                                                   
                include!("autocxxgen.h");                                                              
            }                                                                                          
        }                                                                                              
        #[allow(unused_imports)]                   
        use bindgen::root;                                                                             
        pub mod A {                                                                                    
            pub use super::bindgen::root::A::kConstant;                                                
        }                                          
    }   
 ```

resulting in this error:

```
test /tmp/.tmp1VWb5K/input.rs ... error                                                                
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈                                           
error[E0432]: unresolved import `super::bindgen::root::A`  
 --> $DIR/12185351534412246157.rs:1:1240         
  |                                                                                                    
1 | ...t ; pub mod A { pub use super :: bindgen :: root :: A :: kConstant ; } }
  |                                                        ^ could not find `A` in `root`              
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈                                           
                                                                  
```
 
If I understand right, the `A` from `bindgen::root` needs to be aliased in `ffi::bindgen::root`. (Which might be done via `bindgen_mod_item`? I haven't tried.)

**Comment by adetaylor** [comment]
So, the output you're seeing is:

1. The original bindgen output, before we modify it (listed as "Bindings: ")
2. Then, the modified version after autocxx has changed various bits (listed as "New bindings")

The constant is disappearing between the first and the second. Not sure why.

**Comment by ssbr** [comment]
Aha, okay.

I'll try to trace through and understand why myself, since I wanted to fix this bug so as to learn how autocxx works. :)

**Comment by ssbr** [comment]
Tracing through, I think it's just placed into bindgen via bindgen_mod_item here, so maybe this is exactly how to do it?

```
ApiDetail::Const { const_item } => RsCodegenResult {
                global_items: Vec::new(),
                impl_entry: None,
                bridge_items: Vec::new(),
                extern_c_mod_item: None,
                bindgen_mod_item: Some(Item::Const(const_item)),
                materialization: Use::UsedFromBindgen,
            },
```

I'll upload an updated version, this feels much better.

**Comment by adetaylor** [comment]
Yep, that's exactly what I had in mind... as I mentioned over chat, I've a feeling I tried this in the past and something went wrong but I can't remember what... if it works though, that'd be great!

**Comment by ssbr** [comment]
All tests pass, and the output looked appropriate to me (although a bit weird with all those extra `use`s, I guess they're intended). Outputs:

```
test result: ok. 183 passed; 0 failed; 20 ignored; 0 measured; 0 filtered out; finished in 286.38s
```

```
        mod bindgen {                                                                                  
            pub(super) mod root {                                                                      
                pub mod A {                                                                            
                    pub const kConstant: ::std::os::raw::c_int = 3;                                    
                    #[allow(unused_imports)]                                                           
                    use self::super::super::super::cxxbridge;                                          
                    #[allow(unused_imports)]                                                           
                    use self::super::super::super::ToCppString;                                        
                    #[allow(unused_imports)]       
                    use self::super::super::root;
                }                                                                                      
                #[allow(unused_imports)]                                                               
                use self::super::super::cxxbridge;                                                     
                #[allow(unused_imports)]                                                               
                use self::super::super::ToCppString;                                                   
                #[allow(unused_imports)]
                use self::super::root;                                                                 
            }                                      
        }                                                                                              
        #[cxx::bridge]
        mod cxxbridge {                                                                                
            unsafe extern "C++" {                                                                      
                fn make_string(str_: &str) -> UniquePtr<CxxString>;                                    
                include!("input.h");                                                                   
                include!("autocxxgen.h");          
            }                                      
        }                                                                                              
        #[allow(unused_imports)]            
        use bindgen::root;                         
        pub mod A {                                
            pub use super::bindgen::root::A::kConstant;      
        }
```

(I assume something else may have changed since you last tried.)

Thanks for your patience and help! I think at least on my end, I'm happy with the PR now, and have no more worries, so please feel free to review it at your convenience (no rush on my end).

**Comment by ssbr** [comment]
(edited PR description to take current version of PR into account)

**Comment by adetaylor** [comment]
Thanks!

**Pull request merged**
