### PR TITLE
clippy fixes

### PR DESCRIPTION
**Pull request by philipcraig**
Clippy fixes found as part of #796

### CODE REVIEW

**Comment by adetaylor** [comment]
Thanks for this! It threw up a test failure as well as a rustfmt problem - could you take a look?

**Comment by philipcraig** [comment]
> Thanks for this! It threw up a test failure as well as a rustfmt problem - could you take a look?

I will look into the test failure. About the rust format problem, it looks like an infrastructure issue. This is the error:

```
[3](https://github.com/google/autocxx/runs/5188628464?check_suite_focus=true#step:4:3)s
Run mbrobbel/rustfmt-check@master
  with:
    token: ***
/home/runner/.cargo/bin/cargo + fmt -- -l
/home/runner/work/autocxx/autocxx/engine/src/ast_discoverer.rs
Error: Resource not accessible by integration
```

do you think code changes could lead to that issue?

**Comment by adetaylor** [comment]
Yes, it's because the rustfmt action is trying to add a commit with fixed formatting and it can't write to your branch. Please go to the root of the `autocxx` repository and run `cargo fmt`, then commit that; it should fix it.

**Comment by adetaylor** [comment]
Raised #805 to note that the rustfmt bot is a bit broken anyway.

**Comment by philipcraig** [comment]
> Raised #805 to note that the rustfmt bot is a bit broken anyway.

I am already working on a rust format bot change as part of #796

**Comment by philipcraig** [comment]
Found the (silly) test failures introduced and did `cargo fmt`, please give the workflows another try

**Comment by philipcraig** [comment]
`cargo fmt` and `cargo test --all` pass locally on my Ubuntu now

**Pull request merged**
