### PR TITLE
Pass nonpod by value

### PR DESCRIPTION
**Pull request by adetaylor**
When existing C++ APIs demand that a non-POD type be passed
by value (e.g. a `std::string` or a struct which is not trivial)
we would like those APIs to be callable from Rust, but by
passing a `UniquePtr<T>` instead.

That's what this PR does.

It's not yet clear that such an approach is sufficiently ergonomic for seamless cxx-style interop with existing Rust APIs. We'll see...

It relies on https://github.com/dtolnay/cxx/pull/218 so we can't merge it yet.

### CODE REVIEW

**Comment by dtolnay** [comment]
https://github.com/dtolnay/cxx/pull/218 (replacement implementation) published in cxx 0.5.1.

**Comment by adetaylor** [comment]
I saw! Exciting!

**Review by dtolnay — COMMENTED** [review]
You're going to want some verification of the placement of non-POD fields before emitting to Rust as public fields. As currently implemented I think this is producing Rust datastructures with field offsets not matching the C++ structures.

```rust
    let cxx = indoc! {"
        S::S(uint32_t i) : i(i) {}
    "};
    let hdr = indoc! {"
        #include <cstdint>
        #include <string>
        struct S {
            explicit S(uint32_t i);
            std::string s;
            uint32_t i;
        };
    "};
    let rs = quote! {
        assert_eq!(ffi::cxxbridge::S_make_unique(1).i, 1);
    };
    run_test(cxx, hdr, rs, &["S"], &[]);
```

```console
STDERR:
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', /tmp/.tmpVbDzJ7/input.rs:1:96
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
```

**Comment by adetaylor** [comment]
Thanks - I'll reply on #18.

**Pull request merged**
