### PR TITLE
Reject arrays

### PR DESCRIPTION
**Pull request by adetaylor**
Builds on #370.

### CODE REVIEW

**Comment by thomaseizinger** [comment]
Testing this locally now.

**Comment by thomaseizinger** [comment]
@googlebot I consent.

**Comment by thomaseizinger** [comment]
Can confirm that this fixes the issue with the closure in my project! :)

**Comment by adetaylor** [comment]
Awesome! Thanks for testing!

**Comment by thomaseizinger** [comment]
The build process now aborts with 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 
InvalidCxx(Syn(Error([
	  "unsupported vector element type",
	  "unsupported type: size_t",
	  "unsupported type: AutocxxConcrete38",
	  "unsupported type: AutocxxConcrete39",
	  "unsupported type: AutocxxConcrete41",
	  "unsupported type: AutocxxConcrete42",
	  "unsupported type: AutocxxConcrete44"
])))', build.rs:10:6
```

but I _think_ that is unrelated to this fix.

**Comment by adetaylor** [comment]
Yes, that seems unrelated. I'll aim to get the preprocessor mode working properly over the next couple of days and figure out what's going on here.

**Comment by thomaseizinger** [comment]
Thank you for your help :) (and making autocxx!)

**Pull request merged**
