### PR TITLE
Ignore protected and private types

### LINKED ISSUE #709: Ignore protected inner classes/structs
I'm having an issue where I'm trying to bind to a header which contains a class which contains a protected structure: the bindings reference the protected structure, which is causing issues.

### PR DESCRIPTION
**Pull request by benesch**
@adetaylor just dropping the type at parse time might be too big of a hammer, but it seems to do the trick. Also this depends on adetaylor/rust-bindgen#7; I left the `[patch]` directive in Cargo.toml in case you want to get a CI run on this before merging the bindgen change.

Fix #709.
Supersedes #710.

Co-authored-by: Nikhil Benesch <nikhil.benesch@gmail.com>

- [x] Tests pass
- [x] Appropriate changes to README are included in PR

### CODE REVIEW

**Comment by adetaylor** [comment]
Thanks for this!

I'd prefer not to discard the items at parse time, but instead reject them at a later stage when they can be replaced with an `Api::IgnoredItem`. The intention is that this will result in diagnostics in VSCode or any other `rust-analyzer` based IDE, because a dummy item will be generated which includes a doc string explaining why autocxx can't generate bindings.

Generally speaking `src/conversion/analysis/pod/mod.rs` is the module responsible for Doing Stuff With Types (it's a bit misnamed nowadays - one day I'll rename it). Hopefully all you should need to do is to return an error code from `analyze_struct` in that file, when you encounter a type which is not public. That should be all you need to do to end up with the item being _ignored_ and replaced with diagnostics.

**Comment by benesch** [comment]
Ah yeah, I had a feeling that I was cutting corners, but I didn't want to go to the hassle of plumbing the additional struct property through all the passes without some guidance. Done as you suggest! I introduced a new `Box<StructDetails>` container to match the `FuncToConvert`. It looks a bit silly with just one field, but I figured it would pay dividends as more properties get added. If you think that's unlikely, happy to drop the `Box`, or drop the `StructDetails` container entirely and just plumb the `CppVisibility` type through directly.

(At any point feel free to just take over the PR, too, if the code review back and forth is more trouble than it's worth!)

**Comment by adetaylor** [comment]
Thanks for this! It's really close.

You're running into an inconsistency in the existing code - for structs, we simply pass the entire `syn` `ItemStruct` through the parsing phase and into the analysis phases, whereas for functions we dismantle the `Item` in the parsing phase.

So, at the moment, the information you're packaging up is redundant because it's stored in the `ItemStruct`.

I think that's OK though. I want to move towards dismantling data structures in the parsing phase over time, in case we ever move away from bindgen as the parsing engine.

So, just one request: could you move the `ItemStruct` _into_ your new `StructDetails` type?

Happy to do that myself when I get to merging this, hopefully fairly soon. It's great, thanks!

**Comment by benesch** [comment]
Oh for sure! Done as requested.

**Comment by adetaylor** [comment]
#713 bumps autocxx-bindgen to include your changes so it should be possible to remove the patch section.

**Comment by adetaylor** [comment]
#713 bumps autocxx-bindgen to include your changes so it should be possible to remove the patch section.

**Comment by benesch** [comment]
Amazing! Rebased with the patch directive removed.

**Comment by adetaylor** [comment]
Thanks very much for the contribution! Let me know if it would be helpful for me to spin a new release soon including this, otherwise I will likely make a new release in a couple of weeks accumulating this and whatever other fixes come along.

**Comment by benesch** [comment]
> Thanks very much for the contribution! Let me know if it would be helpful for me to spin a new release soon including this, otherwise I will likely make a new release in a couple of weeks accumulating this and whatever other fixes come along.

No rush at all! I'm working on a [new set of bindings to libprotobuf](https://github.com/MaterializeInc/rust-protobuf-native/), but I've split the project into two separate crates. protobuf-native is a high-level, safe, relative ergonomic Rust API, while protobuf-sys contains autocxx-generated bindings. Right now I'm hand writing `#[cxx::bridge]` blocks in protobuf-native, since there's too much that autocxx doesn't support. But over time I hope that autocxx will be able to generate a complete set of bindings in protobuf-sys, and then protobuf-native won't need to contain any `#[cxx::bridge]` blocks at all!

The upshot is that as autocxx improves I'll add the newly-generable types to protobuf-sys, but it's not actively blocking my work on protobuf-native!

**Pull request merged**
